config/routes.rb
Rails.application.routes.draw do

  namespace :api do 
    namespace :v1 do
      resources :playoff_brackets
      resources :players
      resources :games
      resources :teams
      resources :users
      post "/login", to: "auth#login"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/playoff_bracket.rb
class PlayoffBracket < ApplicationRecord
    belongs_to :user
    has_many :teams

    def finalsfavorite
        #return team with most wins predicted
    end

end

app/controllers/api/playoff_brackets_controller.rb
class Api::V1::PlayoffBracketsController < ApplicationController
  before_action :set_playoff_bracket, only: %i[ show edit update destroy ]

  # GET /playoff_brackets or /playoff_brackets.json
  def index
    @playoff_brackets = PlayoffBracket.all
    render json: @playoff_brackets
  end

  # GET /playoff_brackets/1 or /playoff_brackets/1.json
  def show
    playoff_bracket = PlayoffBracket.find(params[:id])
    render json: playoff_bracket
  end

  # GET /playoff_brackets/new
  def new
    @playoff_bracket = PlayoffBracket.new
  end

  # POST /playoff_brackts or /playoff_brackts.json
  def create
    @playoff_bracket = PlayoffBracket.new(playoff_bracket_params)
  end

  # PATCH/PUT /playoff_brackts/1 or /playoff_brackts/1.json
  def update
    playoff_bracket = PlayoffBracket.find(params[:id])
    playoff_bracket.update(:user_id params[:user_id], :teams params[:teams])
  end

  # DELETE /playoff_brackts/1 or /playoff_brackts/1.json
  def destroy
    playoff_bracket = PlayoffBracket.find(params[:id])
    player.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playoff_bracket
      @playoff_bracket = PlayoffBracket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def playoff_bracket_params
      params.fetch(:playoff_bracket, {})
    end
end

app/controllers/api/v1/playoff_brackets_controller.rb
class Api::V1::PlayoffBracketsController < ApplicationController
  before_action :set_playoff_bracket, only: %i[ show edit update destroy ]

  # GET /playoff_brackets or /playoff_brackets.json
  def index
    @playoff_brackets = PlayoffBracket.all
    render json: @playoff_brackets
  end

  # GET /playoff_brackets/1 or /playoff_brackets/1.json
  def show
    playoff_bracket = PlayoffBracket.find(params[:id])
    render json: playoff_bracket
  end

  # GET /playoff_brackets/new
  def new
    @playoff_bracket = PlayoffBracket.new
  end

  # POST /playoff_brackts or /playoff_brackts.json
  def create
    @playoff_bracket = PlayoffBracket.new(playoff_bracket_params)
  end

  # PATCH/PUT /playoff_brackts/1 or /playoff_brackts/1.json
  def update
    playoff_bracket = PlayoffBracket.find(params[:id])
    # playoff_bracket.update(:user_id params[:user_id], :teams params[:teams])
  end

  # DELETE /playoff_brackts/1 or /playoff_brackts/1.json
  def destroy
    playoff_bracket = PlayoffBracket.find(params[:id])
    player.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playoff_bracket
      @playoff_bracket = PlayoffBracket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def playoff_bracket_params
      params.fetch(:playoff_bracket, {})
    end
end

app/controllers/playoff_brackets_controller.rb
class PlayoffBracketsController < ApplicationController
  before_action :set_playoff_bracket, only: %i[ show edit update destroy ]

  # GET /playoff_brackets or /playoff_brackets.json
  def index
    @playoff_brackets = PlayoffBracket.all
  end

  # GET /playoff_brackets/1 or /playoff_brackets/1.json
  def show
  end

  # GET /playoff_brackets/new
  def new
    @playoff_bracket = PlayoffBracket.new
  end

  # GET /playoff_brackets/1/edit
  def edit
  end

  # POST /playoff_brackets or /playoff_brackets.json
  def create
  end

  # PATCH/PUT /playoff_brackets/1 or /playoff_brackets/1.json
  def update
  end

  # DELETE /playoff_brackets/1 or /playoff_brackets/1.json
  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playoff_bracket
      @playoff_bracket = PlayoffBracket.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def playoff_bracket_params
      params.fetch(:playoff_bracket, {})
    end
end

app/helpers/playoff_brackets_helper.rb
module PlayoffBracketsHelper
end

app/views/playoff_brackets/_form.html.erb
<%= form_with(model: playoff_bracket) do |form| %>
  <% if playoff_bracket.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(playoff_bracket.errors.count, "error") %> prohibited this playoff_bracket from being saved:</h2>

      <ul>
        <% playoff_bracket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/playoff_brackets/_playoff_bracket.html.erb
<div id="<%= dom_id playoff_bracket %>">
</div>

app/views/playoff_brackets/edit.html.erb
<h1>Editing playoff bracket</h1>

<%= render "form", playoff_bracket: @playoff_bracket %>

<br>

<div>
  <%= link_to "Show this playoff bracket", @playoff_bracket %> |
  <%= link_to "Back to playoff brackets", playoff_brackets_path %>
</div>

app/views/playoff_brackets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Playoff brackets</h1>

<div id="playoff_brackets">
  <% @playoff_brackets.each do |playoff_bracket| %>
    <%= render playoff_bracket %>
    <p>
      <%= link_to "Show this playoff bracket", playoff_bracket %>
    </p>
  <% end %>
</div>

<%= link_to "New playoff bracket", new_playoff_bracket_path %>

app/views/playoff_brackets/new.html.erb
<h1>New playoff bracket</h1>

<%= render "form", playoff_bracket: @playoff_bracket %>

<br>

<div>
  <%= link_to "Back to playoff brackets", playoff_brackets_path %>
</div>

app/views/playoff_brackets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @playoff_bracket %>

<div>
  <%= link_to "Edit this playoff bracket", edit_playoff_bracket_path(@playoff_bracket) %> |
  <%= link_to "Back to playoff brackets", playoff_brackets_path %>

  <%= button_to "Destroy this playoff bracket", @playoff_bracket, method: :delete %>
</div>